<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-UOVJQ5N" failures="2" tests="2" name="Test(failed)" time="0.116" errors="0" timestamp="2023-05-10T15:05:05 IST">
  <testcase classname="test.ng.failed.xml.Example2" name="TC4" time="0.022">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
at test.ng.failed.xml.Example2.TC4(Example2.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TC4 -->
  <testcase classname="test.ng.failed.xml.Example2" name="TC5" time="0.002">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
at test.ng.failed.xml.Example2.TC5(Example2.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TC5 -->
  <testcase classname="test.ng.failed.xml.Example2" name="TC3" time="0.0">
    <ignored/>
  </testcase> <!-- TC3 -->
</testsuite> <!-- Test(failed) -->
